# Generated by Django 5.1.6 on 2026-09-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=500)),
                ('image', models.ImageField(max_length=500, null=True, upload_to='Posts/images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
