# Generated by Django 5.1.6 on 2026-09-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_cat_posts_cato'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sl',
            field=models.SlugField(default='sonsdvsdv', unique=True),
            preserve_default=False,
        ),
    ]
