# Generated by Django 5.1.6 on 2026-09-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='sl',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
