# Generated by Django 5.1.6 on 2026-09-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_alter_posts_sl'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
